trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'
  nodeVersion: '20'

stages:
- stage: BuildAndTest
  jobs:
  - job: Backend
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
    - script: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pytest -q
      displayName: 'Install & test backend'
  - job: Frontend
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
    - script: |
        cd frontend
        npm ci || npm i
        npm run build
      displayName: 'Install & build frontend'

# Optional: add a Deploy stage to Azure Web App / Container Registry once service connection is ready.
