name: Publish Docker images (GHCR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

# Prevent cancel on rapid pushes for this workflow
concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [ backend, frontend ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch builds optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional: restore GitHub Actions cache for Docker layers
      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/devops-demo-${{ matrix.service }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
